baseURL = 'http://example.org/'
title = 'åŠ æ‰“åœ°åœ–'
theme = "universal"
languageCode = 'zh-tw'
defaultContentLanguage = 'zh-tw'
# googleAnalytics = "UA-XXXXX-X"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[params]
    disabled_logo = false
    logo_text = "maptwca"
    logo = "img/logo-map.jpg"
    logo_small = "img/logo-map.jpg"
    defaultKeywords = ["", ""]
    defaultDescription = ""
    # default_sharing_image = "img/sharing-default.png"
    facebook_site = "https://www.facebook.com/maptwca/"
    date_format = "January 6, 2006"
    style = "default"

# [params.topbar]
#     enable = true
#     text = "<p>æœ€æ–°è¨Šæ¯ï¼š</p>"

[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "æº–å‚™å¥½é–‹å§‹æ‰“å·¥åº¦å‡äº†å—ï¼Ÿ"
    subtitle = "è·Ÿè‘— ğŸŒ åŠ æ‰“åœ°åœ– çš„æ•™å­¸ï¼Œè¼•é¬†å®Œæˆç”³è«‹å§ï¼"
    link_url = "/iec/pool"
    link_text = "å…¥æ± æŠ½ç±¤"

[params.recent_posts]
    enable = false
    title = "æœ€æ–°æ–‡ç« "
    subtitle = "æœ€æ–°æ–‡ç« "
    hide_summary = true

[params.widgets]
    search = true
    categories = false
    tags = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"


[menu]

[[menu.main]]
    name       = "Home"
    identifier = "memu.home"
    url        = "/"
    weight     = 1
    
[[menu.main]]
    name       = "æ‰“å·¥åº¦å‡"
    identifier = "memu.iec"
    url        = ""
    weight     = 2

[[menu.main]]
    name       = "æ‰“å·¥åº¦å‡ç”³è«‹"
    identifier = "section.iec_apply"
    parent     = "memu.iec"
    weight     = 1
    post       = 3

[[menu.main]]
    name       = "å…¥æ± æŠ½ç±¤"
    url        = "/iec/pool"
    weight     = 1
    parent     = "section.iec_apply"

[[menu.main]]
    name       = "éäº¤è³‡æ–™"
    url        = "/iec/file"
    weight     = 2
    parent     = "section.iec_apply"

[[menu.main]]
    name       = "å…¥å¢ƒå¿…éœ€"
    identifier = "section.entry"
    parent     = "memu.iec"
    weight     = 1
    post       = 4

# [[menu.main]]
#     name       = "è¡Œå‰æº–å‚™"
#     url        = "/test"
#     weight     = 1
#     parent     = "section.entry"

[[menu.main]]
    name       = "æ©Ÿå ´å…¥å¢ƒæµç¨‹"
    url        = "/iec/airport"
    weight     = 2
    parent     = "section.entry"

[[menu.main]]
    name       = "eTA"
    url        = "/iec/eta"
    weight     = 3
    parent     = "section.entry"

[[menu.main]]
    name       = "é†«ç™‚ä¿éšª"
    url        = "/iec/insurance"
    weight     = 4
    parent     = "section.entry"

[[menu.main]]
    name       = "ç¤¾æœƒä¿éšªè™Ÿç¢¼ï¼ˆSINï¼‰"
    url        = "/iec/sin"
    weight     = 5
    parent     = "section.entry"

[[menu.main]]
    name       = "åœ¨åŠ ç”Ÿæ´»"
    identifier = "memu.life"
    url        = ""
    weight     = 3

[[menu.main]]
    name       = "æ—¥å¸¸è³‡è¨Š"
    identifier = "section.info"
    parent     = "memu.life"
    weight     = 1
    post       = 3

[[menu.main]]
    name       = "å„çœæ¯”è¼ƒ"
    url        = "/life/provinces"
    weight     = 1
    parent     = "section.info"

[[menu.main]]
    name       = "äº¤é€š"
    url        = "/life/transportation"
    weight     = 2
    parent     = "section.info"

[[menu.main]]
    name       = "æ¶ˆè²»è³¼ç‰©"
    url        = "/life/shopping"
    weight     = 3
    parent     = "section.info"

[[menu.main]]
    name       = "å…¶ä»–å¯¦ç”¨ç¶²ç«™ï¼ˆå»ºç½®ä¸­ ğŸš§ï¼‰"
    url        = "/life/sites"
    weight     = 4
    parent     = "section.info"

[[menu.main]]
    name       = "é‡é»å¿…å‚™"
    identifier = "section.need"
    url        = ""
    parent     = "memu.life"
    weight     = 1
    post       = 4

[[menu.main]]
    name       = "ç§Ÿå±‹"
    url        = "/life/rent"
    weight     = 1
    parent     = "section.need"

[[menu.main]]
    name       = "éŠ€è¡Œé–‹æˆ¶/ä¿¡ç”¨å¡ï¼ˆå»ºç½®ä¸­ ğŸš§ï¼‰"
    url        = "/life/bank"
    weight     = 2
    parent     = "section.need"

[[menu.main]]
    name       = "æ‰‹æ©Ÿé›»ä¿¡"
    url        = "/life/phone"
    weight     = 3
    parent     = "section.need"

[[menu.main]]
    name       = "é§•ç…§æ›ç™¼"
    url        = "/life/license"
    weight     = 4
    parent     = "section.need"

[[menu.main]]
    name       = "å ±ç¨…"
    url        = "/life/tax"
    weight     = 5
    parent     = "section.need"

[[menu.main]]
    name       = "ç§»æ°‘å°ˆå€"
    identifier = "memu.immigration"
    url        = ""
    weight     = 3

[[menu.main]]
    name       = "äº‹å‰éœ€çŸ¥"
    identifier = "section.preparation"
    url        = ""
    parent     = "memu.immigration"
    weight     = 1
    post       = 2

[[menu.main]]
    name       = "æœ€æ–°æ¶ˆæ¯ âœ´ï¸"
    url        = "/immigration/news"
    weight     = 1
    parent     = "section.preparation"

[[menu.main]]
    name       = "æº–å‚™çŸ¥è­˜"
    url        = "/immigration/knowledge"
    weight     = 2
    parent     = "section.preparation"

[[menu.main]]
    name       = "ç­–ç•¥è¦åŠƒ"
    url        = "/immigration/plans"
    weight     = 3
    parent     = "section.preparation"

[[menu.main]]
    name       = "é¡åˆ¥"
    identifier = "section.category"
    url        = ""
    parent     = "memu.immigration"
    weight     = 1
    post       = 3

[[menu.main]]
    name       = "è¯é‚¦å¿«é€Ÿé€šé“ï¼ˆEEï¼‰"
    url        = "/immigration/ee"
    weight     = 1
    parent     = "section.category"

[[menu.main]]
    name       = "çœæåï¼ˆPNPï¼‰"
    url        = "/immigration/pnp"
    weight     = 2
    parent     = "section.category"

[[menu.main]]
    name       = "å…¶ä»–é¡åˆ¥ï¼ˆå»ºç½®ä¸­ ğŸš§ï¼‰"
    url        = "/immigration/others"
    weight     = 3
    parent     = "section.category"

[[menu.main]]
    name       = "å®Œæˆç”³è«‹"
    identifier = "section.after"
    url        = ""
    parent     = "memu.immigration"
    weight     = 1
    post       = 4

[[menu.main]]
    name       = "å¾ŒçºŒæ­¥é©Ÿ"
    url        = "/immigration/after"
    weight     = 1
    parent     = "section.after"

[[menu.main]]
    name       = "æ‰€éœ€æ–‡ä»¶"
    url        = "/immigration/documents"
    weight     = 2
    parent     = "section.after"

[[menu.main]]
    name       = "é€²åº¦æŸ¥è©¢ï¼ˆTrackerï¼‰"
    url        = "/immigration/tracker"
    weight     = 3
    parent     = "section.after"

[[menu.main]]
    name       = "å•é¡Œè™•ç†"
    url        = "/immigration/problems"
    weight     = 4
    parent     = "section.after"

[[menu.main]]
    name       = "Contact"
    identifier = "memu.faq"
    url        = "/contact"
    weight     = 4
